l_japanese:
  # スペシャルプロジェクト
  show_settings_game_start_chain_title:0 "ゲーム設定の表示"
  show_settings_game_start_chain_desc:0 "$SHOW_SETTING_01$$SHOW_SETTING_02$$SHOW_SETTING_03$$SHOW_SETTING_04$$SHOW_SETTING_05$$SHOW_SETTING_06$$SHOW_SETTING_07$$SHOW_SETTING_08$$SHOW_SETTING_09$$SHOW_SETTING_10$$SHOW_SETTING_11$$SHOW_SETTING_12$$SHOW_SETTING_13$$SHOW_SETTING_14$$SHOW_SETTING_15$$SHOW_SETTING_16$$SHOW_SETTING_17$$SHOW_SETTING_18$$SHOW_SETTING_19$$SHOW_SETTING_20$$SHOW_SETTING_21$$SHOW_SETTING_22$$SHOW_SETTING_23$$SHOW_SETTING_24$$SHOW_SETTING_25$$SHOW_SETTING_26$$SHOW_SETTING_27$$SHOW_SETTING_28$$SHOW_SETTING_29$$SHOW_SETTING_30$"

  ####
  # show_settings_game_start_chain_descの中身編集用
  # コメントのある空行は、判別の仕方がわからなかったもの
  ####
  SHOW_SETTING_01:0 "§L$GALAXY_SIZE$§!§W: [This.GetGalaxySize]§!\n"
  SHOW_SETTING_02:0 "§L$GALAXY_SHAPE$§!§W: [This.GetGalaxyShape]§!\n"
  SHOW_SETTING_03:0 "§L$NUM_EMPIRES$§!§W: [This.setup_value_num_empires]§!\n"
  SHOW_SETTING_04:0 "§L$NUM_ADVANCED_EMPIRES$§!§W: [This.setup_value_num_advanced_empires]§!\n"
  SHOW_SETTING_05:0 "§L$NUM_FALLEN_EMPIRES$§!§W: [This.setup_value_num_fallen_empires]§!\n"
  SHOW_SETTING_06:0 "§L$NUM_MARAUDER_EMPIRES$§!§W: [This.setup_value_num_marauder_empires]§!\n"
  SHOW_SETTING_07:0 "§L$FE_TECH_SPEED$§!§W: [This.setup_value_tech_costs_scale]x§!\n"
  SHOW_SETTING_08:0 "§L$NUM_HABITABLE_WORLDS$§!§W: [This.setup_value_habitable_worlds_scale]x§!\n"
  SHOW_SETTING_09:0 "§L$FE_PRIMITIVE_WORLDS$§!§W: [This.setup_value_primitive_worlds_scale]x§!\n"
  SHOW_SETTING_10:0 "§L$FE_CRISES$§!§W: [This.setup_value_crisis_strength_scale]x([This.GetCrisisStrengthValue]x)§!\n"
  SHOW_SETTING_11:0 "§L$CRISIS_TYPE_LABEL$§!§W: [This.GetAllowedCrisisType]§!\n"
  SHOW_SETTING_12:0 "§L$FE_MID_GAME$§!§W: [This.setup_value_mid_game_year]§!\n"
  SHOW_SETTING_13:0 "§L$FE_END_GAME$§!§W: [This.setup_value_end_game_year]§!\n"
  SHOW_SETTING_14:0 "§L$FE_VICTORY$§!§W: [This.setup_value_victory_year]§!\n"
  SHOW_SETTING_15:0 "§L$FE_DIFFICULTY$§!§W: [This.GetDifficulty]§!\n"
  # FE_SCALING_DIFFICULTY
  SHOW_SETTING_16:0 ""
  # DIFFICULTY_ADJUSTED_AI_MODIFIERS
  SHOW_SETTING_17:0 ""
  # FE_AGGRESSIVENESS
  SHOW_SETTING_18:0 ""
  # FE_CLUSTERED_STARTS
  SHOW_SETTING_19:0 ""
  # FE_ADVANCED_NEAR_PLAYER
  SHOW_SETTING_20:0 ""
  SHOW_SETTING_21:0 "§L$NUM_HYPERLANES$§!§W: [This.setup_value_num_hyperlanes]x§!\n"
  SHOW_SETTING_22:0 "§L$NUM_GATEWAYS$§!§W: [This.setup_value_num_gateways]x§!\n"
  SHOW_SETTING_23:0 "§L$NUM_WORMHOLES$§!§W: [This.setup_value_num_wormhole_pairs]x§!\n"
  # FE_GUARANTEED_COLONIES
  SHOW_SETTING_24:0 ""
  SHOW_SETTING_25:0 "§L$CARAVANEERS_LABEL$§!§W: [This.GetCaravaneersEnabled]§!\n"
  SHOW_SETTING_26:0 "§L$LGATE_LABEL$§!§W: [This.GetLGateEnabled]§!\n"
  SHOW_SETTING_27:0 "§L$XENO_COMPATIBILITY_LABEL$§!§W: [This.GetXenoCompatibilityEnabled]§!\n"
  # FE_LOGISTIC_CEILING
  SHOW_SETTING_28:0 ""
  # FE_GROWTH_SCALE
  SHOW_SETTING_29:0 ""
  SHOW_SETTING_30:0 "§L$FE_IRONMAN$§!§W: [This.GetIsIronman]§!\n"
